# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "lucid32"

  # config.vm.box_url = "http://domain.com/path/to/above.box"

  config.vm.forward_port 80, 8008

   config.vm.provision :puppet do |puppet|
     puppet.facter = {"fqdn" => "local.test"}
     puppet.manifests_path = "./manifests"
     puppet.manifest_file  = "site.pp"
   end
end
